import Link from "next/link";
import { getChatGPTUser } from "./chatgpt-auth";

export const dynamic = "force-dynamic";

export default async function Home() {
  const user = await getChatGPTUser();
  return <main className="landing">
    <nav className="landing-nav"><Link className="landing-brand" href="/"><span>C</span>CashFlo</Link><div><a href="#how-it-works">How it works</a><a href="#features">Features</a>{user ? <Link className="landing-cta small" href="/app">Open dashboard</Link> : <a className="landing-cta small" href="/signin-with-chatgpt?return_to=/app">Sign in with ChatGPT</a>}</div></nav>
    <section className="landing-hero"><div><span className="landing-kicker">AI FINANCIAL CLARITY FOR SMALL BUSINESSES</span><h1>Turn your financial statements into decisions.</h1><p>Upload your Income Statement, Balance Sheet, and Cash Flow Statement. CashFlo translates them into clear KPIs, operating concerns, practical recommendations, and owner-ready reports.</p><div className="landing-actions">{user ? <Link className="landing-cta" href="/app">Open your dashboard →</Link> : <a className="landing-cta" href="/signin-with-chatgpt?return_to=/app">Start securely with ChatGPT →</a>}<a className="landing-secondary" href="#how-it-works">See how it works</a></div><div className="trust-row"><span>✓ Raw workbooks stay in your browser</span><span>✓ Private account data</span><span>✓ Flexible monthly or annual periods</span></div></div><div className="landing-preview"><div className="preview-top"><span>Financial health</span><b>82 <small>/ 100</small></b></div><h3>Cash is stable, with stronger year-end momentum.</h3><div className="preview-kpis"><div><small>Cash</small><b>$107.8K</b></div><div><small>Revenue</small><b>$1.40M</b></div><div><small>Net income</small><b>$52.8K</b></div></div><div className="preview-insight"><i>✦</i><p><b>AI CFO brief</b><span>Protect cash conversion while revenue grows.</span></p></div></div></section>
    <section className="how" id="how-it-works"><span className="landing-kicker">HOW IT WORKS</span><h2>From statements to an operating plan in minutes.</h2><div className="how-grid"><article><span>01</span><h3>Upload three statements</h3><p>Use one Excel workbook or separate Excel and CSV files. Single month, annual, and monthly-column formats are supported.</p></article><article><span>02</span><h3>Review normalized KPIs</h3><p>CashFlo recognizes common statement labels and calculates profitability, liquidity, cash quality, and financial health.</p></article><article><span>03</span><h3>Act on the priorities</h3><p>Receive operating concerns, a 90-day action plan, AI CFO answers, and a printable management report.</p></article></div></section>
    <section className="feature-section" id="features"><div><span className="landing-kicker">BUILT FOR OWNERS</span><h2>Financial intelligence without finance jargon.</h2><p>CashFlo focuses on the questions a small-business owner actually needs answered.</p></div><div className="feature-grid"><article><i>▦</i><h3>Executive dashboard</h3><p>Cash, revenue, profit, margins, liquidity, trends, and financial health in one view.</p></article><article><i>✦</i><h3>AI CFO insights</h3><p>Evidence-based concerns and recommendations grounded in normalized financial metrics.</p></article><article><i>▤</i><h3>Operating reports</h3><p>Print-ready management reporting and KPI exports for monthly owner reviews.</p></article><article><i>◷</i><h3>Private history</h3><p>Keep a secure record of each saved reporting period under your signed-in account.</p></article></div></section>
    <section className="landing-final"><h2>Understand the numbers. Run the business better.</h2>{user ? <Link className="landing-cta" href="/app">Open CashFlo →</Link> : <a className="landing-cta" href="/signin-with-chatgpt?return_to=/app">Create your private workspace →</a>}</section>
    <footer><Link className="landing-brand" href="/"><span>C</span>CashFlo</Link><p>Management planning software. Not accounting, tax, legal, or investment advice.</p></footer>
  </main>;
}
